### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by zlocate** [aa-chernov/aa-chernov.github.io#3]
Здравствуйте
Благодарю за проделанную работу.
К сожалению текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации:

Репозиторий:
**Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
Для их публикации выполните команду `git push origin --tags`
Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8

Регулярные выражения:

Имя
**Нужно исправить** следующие корректные кейсы не проходят валидацию:
Ёлка-Ёлка - второе имя также может начинаться с буквы Ё 
**Нужно исправить** следующие некорректные кейсы проходят валидацию:
`ЗаглавнаяЗаглавная` - Имя может содержать только одну заглавную букву (и она должна быть первой)
`Денис-`  - допустимо или одинарное имя Денис, или двойное Денис-Иван, но не промежуточные варианты :)

Email
**Нужно исправить** регулярное выражение содержит синтаксическую ошибку, из-за чего валидация данного поля работает некорректно
![image](https://user-images.githubusercontent.com/43764701/82124125-b2008d00-97a5-11ea-966f-7420c5339b8d.png)

Студенты иногда сталкиваются с синтаксическими ошибками в регулярных выражениях, обусловленных тем, что в FF и Chrome для регулярок в поле pattern неявно применяется аттрибут /u из ES6, что накладывает ограничения на экранирование символов (например при экранировании @ или . \ cыплется ошибка)
Решение проблемы убрать избыточное экранирование спецсимволов.

**Нужно исправить** следующие некорректные кейсы проходят валидацию:
some@mail - адрес почты должен содержать доменную зону

**Нужно исправить** следующие корректные кейсы не проходят валидацию:
some@yandex.academy - адрес почты может содержать длинную доменную зону. Я рекомендую либо значительно увеличить, либо убрать ограничение на длину сверху для доменной зоны.

**Можно лучше** следующие корректные кейсы не проходят валидацию:

my---mail@site.ru - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным

Номер телефона
**Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.

+7(925 900-90-90
+7925900-90-90
+792590090-90
+7-925-900-90-90
+7 (925) 900-90-90
+7 (925) 9009090
+7(925) 9009090
+7 (925)9009090
+7(925)9009090
+7 925 900-90-90

Адрес сайта
**Нужно исправить**: регулярное выражение содержит синтаксическую ошибку связанную с некорректным экранированием (подробно раскрыто для регулярного выражения email)

![image](https://user-images.githubusercontent.com/43764701/82124406-8d0d1980-97a7-11ea-901e-ad7c862411ad.png)

После исправления просьба убедиться что данные кейсы работают корректно
```
Адрес сайта:
Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
http://ya.ru
https://www.ya.ru
http://google.ru:98/
http://x.com:30
http://google.ru/path/to/deep/
http://my-next-site.ru
http://8.8.8.8:8080
http://8.8.8.8:8080/page/to/deep#
http://some.test.yandex.ru

Негативные кейсы:
Проверку проходит следующий некорректный адреc сайта:
http://www.ya.
http://www (отсутствует доменная зона)
http://.ru (отсутствует доменное имя) 
http:something.ru (отсутствуют `//` после протокола) 
zzz://ya.ru (некорректный протокол. Допустимы только http\https)
http:\\google.ru
 httP://google.ru 
http://google.ru:/path/to/deep
https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
http://something (отсутствует доменная зона)
http://1. (некорректный IP, точка на конце)
http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
http://127. (некорректный IP, точка на конце)
http://127.0..  (некорректный IP, точка на конце)
http://127.0.0.. (некорректный IP, точка на конце) 
http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
https://mysite.23 (tld не может состоять из цифр) 
http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
```

**Comment by aa-chernov** [comment]
## **Исправлено:**

**Имя:**
-  `Ёлка-Ёлка` проходит валидацию.
- ` ЗаглавнаяЗаглавная` не проходит валидацию.
-  `Денис-` не проходит валидацию.

**Email:**
- `some@mail` не проходит валидацию без доменной зоны.
- Для валидации `some@yandex.academy` у доменной зоны убрана верхняя граница.
- `my---mail@site.ru` не проходит валидацию.

**Номер телефона:**

- Номера:
`+7(925 900-90-90`
`+7925900-90-90`
`+792590090-90`
`+7-925-900-90-90`
`+7 (925) 900-90-90`
`+7 (925) 9009090`
`+7(925) 9009090`
`+7 (925)9009090`
`+7(925)9009090`
`+7 925 900-90-90`
в соответствии с требованием, не проходят валидацию.

**Адрес сайта:**
- Регулярное выражение для валидации адреса сайта переработано под указанные требования.

**Общие доработки:**
- Исправлены синтаксические ошибки, связанные с некорректным экранированием в регулярных выражениях.

__v0.0.3:__ [Ссылка на рабочую версию формы](https://aa-chernov.github.io/validation/)

**Comment by aa-chernov** [comment]
> Здравствуйте
> Благодарю за проделанную работу.
> К сожалению текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации:
> 
> Репозиторий:
> **Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
> Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
> Для их публикации выполните команду `git push origin --tags`
> Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8
> 
> Регулярные выражения:
> 
> Имя
> **Нужно исправить** следующие корректные кейсы не проходят валидацию:
> Ёлка-Ёлка - второе имя также может начинаться с буквы Ё
> **Нужно исправить** следующие некорректные кейсы проходят валидацию:
> `ЗаглавнаяЗаглавная` - Имя может содержать только одну заглавную букву (и она должна быть первой)
> `Денис-` - допустимо или одинарное имя Денис, или двойное Денис-Иван, но не промежуточные варианты :)
> 
> Email
> **Нужно исправить** регулярное выражение содержит синтаксическую ошибку, из-за чего валидация данного поля работает некорректно
> ![image](https://user-images.githubusercontent.com/43764701/82124125-b2008d00-97a5-11ea-966f-7420c5339b8d.png)
> 
> Студенты иногда сталкиваются с синтаксическими ошибками в регулярных выражениях, обусловленных тем, что в FF и Chrome для регулярок в поле pattern неявно применяется аттрибут /u из ES6, что накладывает ограничения на экранирование символов (например при экранировании @ или . \ cыплется ошибка)
> Решение проблемы убрать избыточное экранирование спецсимволов.
> 
> **Нужно исправить** следующие некорректные кейсы проходят валидацию:
> some@mail - адрес почты должен содержать доменную зону
> 
> **Нужно исправить** следующие корректные кейсы не проходят валидацию:
> [some@yandex.academy](mailto:some@yandex.academy) - адрес почты может содержать длинную доменную зону. Я рекомендую либо значительно увеличить, либо убрать ограничение на длину сверху для доменной зоны.
> 
> **Можно лучше** следующие корректные кейсы не проходят валидацию:
> 
> [my---mail@site.ru](mailto:my---mail@site.ru) - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
> 
> Номер телефона
> **Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
> 
> +7(925 900-90-90
> +7925900-90-90
> +792590090-90
> +7-925-900-90-90
> +7 (925) 900-90-90
> +7 (925) 9009090
> +7(925) 9009090
> +7 (925)9009090
> +7(925)9009090
> +7 925 900-90-90
> 
> Адрес сайта
> **Нужно исправить**: регулярное выражение содержит синтаксическую ошибку связанную с некорректным экранированием (подробно раскрыто для регулярного выражения email)
> 
> ![image](https://user-images.githubusercontent.com/43764701/82124406-8d0d1980-97a7-11ea-901e-ad7c862411ad.png)
> 
> После исправления просьба убедиться что данные кейсы работают корректно
> 
> ```
> Адрес сайта:
> Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
> http://ya.ru
> https://www.ya.ru
> http://google.ru:98/
> http://x.com:30
> http://google.ru/path/to/deep/
> http://my-next-site.ru
> http://8.8.8.8:8080
> http://8.8.8.8:8080/page/to/deep#
> http://some.test.yandex.ru
> 
> Негативные кейсы:
> Проверку проходит следующий некорректный адреc сайта:
> http://www.ya.
> http://www (отсутствует доменная зона)
> http://.ru (отсутствует доменное имя) 
> http:something.ru (отсутствуют `//` после протокола) 
> zzz://ya.ru (некорректный протокол. Допустимы только http\https)
> http:\\google.ru
>  httP://google.ru 
> http://google.ru:/path/to/deep
> https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
> http://something (отсутствует доменная зона)
> http://1. (некорректный IP, точка на конце)
> http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
> http://127. (некорректный IP, точка на конце)
> http://127.0..  (некорректный IP, точка на конце)
> http://127.0.0.. (некорректный IP, точка на конце) 
> http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
> https://mysite.23 (tld не может состоять из цифр) 
> http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
> ```

@zlocate , добрый день.
Я доработал проект по замечаниям и ответил здесь. Не знаю, читаете ли Вы оставленные здесь комментарии и приходят ли Вам уведомления. Проектная работа в разделе практикума находится на проверке и я не могу загрузить её снова, чтобы уведомить Вас. Если вы читаете это, прошу поделиться обратной связью.

**Comment by zlocate** [comment]
> > Здравствуйте
> > Благодарю за проделанную работу.
> > К сожалению текущая реализация содержит ряд недостатков не позволяющих мне засчитать работу на данной итерации:
> > Репозиторий:
> > **Нужно исправить**: отсутствуют git-теги отражающие номер версии. Создать их можно при помощи команды `git tag -a v0.0.1 -m "my first version"`
> > Обращаю внимание что теги по-умолчанию не публикуются при вызове команды `git push`
> > Для их публикации выполните команду `git push origin --tags`
> > Подробнее: https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8
> > Регулярные выражения:
> > Имя
> > **Нужно исправить** следующие корректные кейсы не проходят валидацию:
> > Ёлка-Ёлка - второе имя также может начинаться с буквы Ё
> > **Нужно исправить** следующие некорректные кейсы проходят валидацию:
> > `ЗаглавнаяЗаглавная` - Имя может содержать только одну заглавную букву (и она должна быть первой)
> > `Денис-` - допустимо или одинарное имя Денис, или двойное Денис-Иван, но не промежуточные варианты :)
> > Email
> > **Нужно исправить** регулярное выражение содержит синтаксическую ошибку, из-за чего валидация данного поля работает некорректно
> > ![image](https://user-images.githubusercontent.com/43764701/82124125-b2008d00-97a5-11ea-966f-7420c5339b8d.png)
> > Студенты иногда сталкиваются с синтаксическими ошибками в регулярных выражениях, обусловленных тем, что в FF и Chrome для регулярок в поле pattern неявно применяется аттрибут /u из ES6, что накладывает ограничения на экранирование символов (например при экранировании @ или . \ cыплется ошибка)
> > Решение проблемы убрать избыточное экранирование спецсимволов.
> > **Нужно исправить** следующие некорректные кейсы проходят валидацию:
> > some@mail - адрес почты должен содержать доменную зону
> > **Нужно исправить** следующие корректные кейсы не проходят валидацию:
> > [some@yandex.academy](mailto:some@yandex.academy) - адрес почты может содержать длинную доменную зону. Я рекомендую либо значительно увеличить, либо убрать ограничение на длину сверху для доменной зоны.
> > **Можно лучше** следующие корректные кейсы не проходят валидацию:
> > [my---mail@site.ru](mailto:my---mail@site.ru) - адрес электронной почы, содержащий несколько символов '-' подряд является некорректным
> > Номер телефона
> > **Нужно исправить**: Данные форматы номеров телефонов проходят валидацию, хотя с точки зрения постановки задачи они являются невалидными.
> > +7(925 900-90-90
> > +7925900-90-90
> > +792590090-90
> > +7-925-900-90-90
> > +7 (925) 900-90-90
> > +7 (925) 9009090
> > +7(925) 9009090
> > +7 (925)9009090
> > +7(925)9009090
> > +7 925 900-90-90
> > Адрес сайта
> > **Нужно исправить**: регулярное выражение содержит синтаксическую ошибку связанную с некорректным экранированием (подробно раскрыто для регулярного выражения email)
> > ![image](https://user-images.githubusercontent.com/43764701/82124406-8d0d1980-97a7-11ea-901e-ad7c862411ad.png)
> > После исправления просьба убедиться что данные кейсы работают корректно
> > ```
> > Адрес сайта:
> > Позитивные кейсы: (только не привязывайтесь к конкретным IP и доменам, я использую при проверке произвольные но соответствующие по сути)
> > http://ya.ru
> > https://www.ya.ru
> > http://google.ru:98/
> > http://x.com:30
> > http://google.ru/path/to/deep/
> > http://my-next-site.ru
> > http://8.8.8.8:8080
> > http://8.8.8.8:8080/page/to/deep#
> > http://some.test.yandex.ru
> > 
> > Негативные кейсы:
> > Проверку проходит следующий некорректный адреc сайта:
> > http://www.ya.
> > http://www (отсутствует доменная зона)
> > http://.ru (отсутствует доменное имя) 
> > http:something.ru (отсутствуют `//` после протокола) 
> > zzz://ya.ru (некорректный протокол. Допустимы только http\https)
> > http:\\google.ru
> >  httP://google.ru 
> > http://google.ru:/path/to/deep
> > https://999.999.999.999/ (у адреса ограничение: в ipv4 каждая часть адреса должна быть целым положительным числом и не больше 8 бит, те: 255)
> > http://something (отсутствует доменная зона)
> > http://1. (некорректный IP, точка на конце)
> > http://ya.ru:00000 (некорректный номер порта, в IPv4 порт это целое число равное максимум 65535, так как это целое число, то несколько нулей подряд являются невалидными) 
> > http://127. (некорректный IP, точка на конце)
> > http://127.0..  (некорректный IP, точка на конце)
> > http://127.0.0.. (некорректный IP, точка на конце) 
> > http://127.0.0.1:8000/$ssss@# (некоректный путь - разрешены только цифры, слешы и латинские буквы, решетка (#) на конце) 
> > https://mysite.23 (tld не может состоять из цифр) 
> > http://www.google.ru/////// (в пути количество слешей подряд должно быть ограничено 1)
> > ```
> 
> @zlocate , добрый день.
> Я доработал проект по замечаниям и ответил здесь. Не знаю, читаете ли Вы оставленные здесь комментарии и приходят ли Вам уведомления. Проектная работа в разделе практикума находится на проверке и я не могу загрузить её снова, чтобы уведомить Вас. Если вы читаете это, прошу поделиться обратной связью.

Проблема устранена. Можете загружать работу на проверку. Приношу извинения за доставленные неудобства.

**Comment by aa-chernov** [comment]
@zlocate Денис, добрый вечер, загрузил на проверку новую версию. Спасибо, что откликнулись. Подскажите, можно, если что, здесь Вам писать?

**Comment by zlocate** [comment]
@aa-chernov да, можете смело писать тут :)

**Comment by zlocate** [comment]
Добрый вечер. Благодарю за ожидание.
Осталась одни критическая проблема, требующая исправления:
Регулярные выражения:
Email
**Нужно исправить** следующие корректные адреса почты не проходят валидацию.
x@gmail.com - имя ящика может состоять из одного символа

**Comment by aa-chernov** [comment]
## **Исправлено:**

**Email:**
- Адрес `m@mail.ru` проходит валидацию.

**Comment by zlocate** [comment]
Добрый день. Отличная работа.
Принято!
Желаю вам успехов в дальнейшем изучении курса :)

**Comment by aa-chernov** [comment]
@zlocate Ура! Спасибо! Я же правильно понимаю, что теперь можно закрыть issue?
